### ISSUE TITLE
Identity Oracle Signature for Contract Inputs

### ISSUE THREAD

**Issue by eamesyi** [tokenized/specification#55]
All inputs (public keys/sigs) should be validated by a signed message from an Identity Oracle(s) to assure any contracting parties that the public keys are associated with the entities involved in the contract (eg. issuer/contract operator for a smart contract, contracting parties for a static contract).  This is probably accomplished best by adding another input(s) for the Identity Oracle(s) using SIGHASH_ALL.

**Comment by KarlTheProgrammer** [comment]
After talking with @eamesyi, this is what we figured out.

**Static Contracts** can use two common methods, or an external method.

1. Have a relationship setup that involved an oracle signature so that both parties can prove the signatures on the static contract came from the party they know.
2. Provide an oracle name, public key, and signature in the static contract that proves the entities listed in the static contract have signed off on the static contract. The signature data will include the entities in the static contract data, the PKHs the transaction is to be signed with, and a recent block hash so the signature will expire and can't be used later.

**Dynamic (Smart) Contracts** can provide an optional oracle signature to prove they are being run by the entities listed. This will be provided when the contract is formed and whenever the administrator address is changed. The signature data will include the entities in the contract data, the PKHs of the administrator/operator, and a recent block hash so the signature will expire and can't be used later. This involves adding a hosting entity to the contract data when the smart contract agent is being run(hosted) by someone other than the contract administrator.

- [ ] Create oracle signature type for contract entities. Specify data for calculating sig hash including list of entity structs, list of PKHs, a recent block hash, and an approved flag. The entities/pkhs must be in the same order as the transaction inputs. 
- [ ] Add optional oracle name, public key, signature to static contract formation, contract offer, and contract amendments.
- [ ] Ensure there is a method of providing an entity for the smart contract agent host.
